### ISSUE TITLE
Add helper function for getting all sitemaps for the index.

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wp-sitemaps#103]
### Description

**Which feature is your enhancement request related to?**
This is a follow-up to #102.

**Describe the solution you'd like**
The implementation for gathering all sitemap entries for the sitemap index is implemented procedurally within the `Core_Sitemaps_Index::render_index()` method, and repeated in the `_get_sitemap_entries()` helper method in the PHPUnit tests.

At present, we've not abstracted this into a separate functional method since it's not reused anywhere else in the codebase, nor would we expect it to be needed for implementations extending or modifying the core functionality, and would introduce backwards compatibility concerns. However, as described in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/102#issuecomment-573209132, abstracting this important functionality would make it easier to test and prevent possible future bugs from being introduced, like #102, during code refactoring.

**Additional context**
I would suggest an implementation, similar to the following...

```
function core_sitemaps_get_sitemap_entries() {
	$sitemaps  = array();
	$providers = core_sitemaps_get_sitemaps();

	foreach ( $providers as $provider ) {
		// Using array_push is more efficient than array_merge in a loop.
		array_push( $sitemaps, ...$provider->get_sitemap_entries() );
	}

	return apply_filters( 'filter_name', $sitemaps );
}
```

Note that the use of the [splat operator](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat) makes this functionality only compatible for PHP 5.6+. To extend compatibility to earlier versions, this could be modified to use `call_user_func_array()` on an array of sitemap entry arrays. See https://github.com/dseguy/clearPHP/blob/master/rules/no-array_merge-in-loop.md for more context.

### Acceptance Criteria
Add the relevant acceptance criteria here.
- [ ] A publicly accessible function/method exists that encapsulates the functionality for gathering all sitemap entries for the index, returning all available sitemap pages data.
- [ ] The new method is covered by new PHPUnit tests.
- [ ] The current places in the codebase where this functionality exists has been updated to make use of the abstracted method.

**Comment by felixarntz** [comment]
Nice, I didn't even see this issue, but I kind of wrote exactly this method in #172. It doesn't have a filter, but that could easily be added. Let's think about whether we'd really need it though first.

Do we want this to also be available as a simple function? While someone could instantiate a `Core_Sitemaps_Index` object and call the method on there, if we want this to be easily usable outside of our codebase we should probably expose a wrapper function that does this, like `core_sitemaps_get_sitemap_entries`. If this is something we only want for our own ease of testing, then I think the method is sufficient.

Thoughts @joemcgill @swissspidy?
