### ISSUE TITLE
Update contributors list.

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wp-sitemaps#107]
### Description

Update the readme file with the full list of contributors. and their WordPress.org.

**Describe the solution you'd like**
We want to make sure everyone who worked on the project receives credit for their work — including the important non-code-related work that was involved.

Current list includes: Sander van Dragt, Kirsty Burgoine, Adrian McSean, Ruxandra Gradina, Joe McGill, Thierry Muller, Pascal Birchler.

**Comment by swissspidy** [comment]
This is for the `readme.txt` _and_ `readme.md`, right?

**Comment by chetansatasiya** [comment]
@joemcgill @swissspidy  I am not sure about other guys so didn't add that. 

@swissspidy I updated the both one.
