### ISSUE TITLE
Add WP-CLI support to force sitemap generation

### ISSUE THREAD

**Issue by lukecav** [GoogleChromeLabs/wp-sitemaps#110]
Include WP-CLI support in order to be able to force sitemap generation to run.

**Comment by joemcgill** [comment]
Great idea. I'd probably leave this to the WP-CLI project to implement and ensure that this plugin has the necessary public API necessary for CLI commands to be supported.

**Comment by lukecav** [comment]
@joemcgill 

Okay will do.
