### ISSUE TITLE
Disable sitemap generation if site is private.

### ISSUE THREAD

**Issue by peterwilsoncc** [GoogleChromeLabs/wp-sitemaps#111]
### Description

Currently the site map reference is not added to `robots.txt` if `! get_option( 'blog_public' )`. In such cases, it may be better to bypass sitemap generation in its entirety.

Pros:
* Sitemap will not instruct search engines to visit pages with `noindex` meta tags
* Less work for the server

Cons:
* Upon setting the blog to public, the sitemap will not exist

**Which feature is your enhancement request related to?**
#24 

**Describe the solution you'd like**
Adding this to the bootstrapping process would do the tick. The `do_robots` action would need to be removed too.

```php
if ( ! get_option( 'blog_public' ) {
	return;
}
```

**Additional context**
Add any other context or screenshots about the enhancement request here.

### Acceptance Criteria
Add the relevant acceptance criteria here.

- [ ] Private sites do not have sitemaps
- [ ] Sitemap is not listed in robots.txt for private sites

**Comment by joemcgill** [comment]
Good suggestion, @peterwilsoncc. Since this is proposed to be a public standard, it makes sense that people would not simply be able to type in the URL for the sitemap to see the contents of the site, even when not exposed by the robots.txt file.
