### ISSUE TITLE
Extract `Core_Sitemaps_Provider` interface

### ISSUE THREAD

**Issue by tangrufus** [GoogleChromeLabs/wp-sitemaps#115]
### Description

**Describe the solution you'd like**

Extract `Core_Sitemaps_Provider` interface.

**Additional context**

Currently, custom providers must `extends Core_Sitemaps_Provider`:

https://github.com/GoogleChromeLabs/wp-sitemaps/blob/69f665dc208fdf07111ed2c9e271a067d382378c/inc/class-core-sitemaps-registry.php#L31-L33

To extract the interface, we need to turn properity accesses (`$provider->route`) to getter methods (`$provider->get_route()`):

https://github.com/GoogleChromeLabs/wp-sitemaps/blob/a2f62c0af63cc3d5f6731d2c9bdbe275284ef03c/inc/class-core-sitemaps.php#L125

### Acceptance Criteria

- [ ] Third party developers are able to add custom providers without subclassing `Core_Sitemaps_Provider`
- [ ] `Core_Sitemaps_Provider_Interface` defines all the necessary methods custom providers need to implement

**Comment by joemcgill** [comment]
Hi @TangRufus. Thanks for the suggestion! I agree that the `Core_Sitemaps_Provider` class is very well suited to be converted to a PHP interface or trait, rather than a parent class.

At present, WordPress Core doesn't make use of interfaces anywhere in the codebase, which is why we had not introduced them here. However, this might be a great opportunity to do so.

**Comment by swissspidy** [comment]
Perhaps we can ask for some feedback on introducing interfaces in #core-php

**Comment by scrobbleme** [comment]
Just a note: if there is no real need to extract an interface, it shouldn't be done.
In this case you may extract an interface, implement a [abstact] class, and others are confused as they basically don't know what to implement.

Generelly, as WordPress is providing hooks anywhere, it is propably never necessary to implement a specific interface/class, which may be the reason, there are not interfaces in core?? (Nevertheless, I would like to see some more "class based" styles in core, i.e. be able to create a new custom post type through inheritence and not filtering)

**Comment by swissspidy** [comment]
Some refactoring is done in #150, and more will follow ahead of the merge proposal. I think creating an interface is currently off the table.

I am closing this one for now. Can always revisit though.
