### ISSUE TITLE
Document branching strategy for community

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#12]
For this project we advocate a slightly simplified [Git Flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) approach, dropping the requirement for a "release" branch. We are not planning to use the specific git-flow plugin for git, but instead rely on a strict naming convention described below.

![Simplified _Git FLow_](https://user-images.githubusercontent.com/103192/66979510-69360800-f0e0-11e9-895c-022275a01735.png)

### Important Notes

- Hotfix branches should be applied to both master and develop, to ensure these stay in sync.
- It is expected that development remains unblocked, so it's important to consider when something should be promoted from a feature branch to develop. Features that are still in testing or experimental should not be merged to develop prematurely. All merged features will need to be confirmed as stable to consider a release candidate.

### Naming Conventions

Release candidate tag: v0.1.0 (major.minor.fix)
Feature branch: feature/issueID*-short-title
Hotfix: hotfix/issueID-short-title 

_* issueID refers to the GitHub issue ID_

**Comment by joemcgill** [comment]
@mcshanea let's confirm that this is the approach we want to take and get this added to our README documentation before closing.
