### ISSUE TITLE
Clarify the SimpleXML dependency

### ISSUE THREAD

**Issue by johnbillion** [GoogleChromeLabs/wp-sitemaps#122]
### Description

**Is your task request related to a problem? Please describe.**

WordPress core uses SimpleXML, but it's not a required extension. For example, code such as `class_exists( 'SimpleXMLElement' )` can be found in several places in core.

The Core Sitemaps plugin declares `ext-simplexml` as a dependency.

**Describe the solution you'd like**

Prior to any merge proposal with core, it needs to be determined whether SimpleXML is a required extension, whether PHP 5.6 as a minimum affects this, behaviour if the extension doesn't exist, etc etc.

**Comment by pbiron** [comment]
I don't have have at the moment to give all my thoughts on this issue, but I wanted to say 2 things now before I forget:

1. using `SimpleXML` (or `XMLWriter`, see number 2) would be highly preferable to using "string concatination" for generating the sitemaps.  But, yes, there are probably some hosts which don't have the extension installed.  It would be really great if we could get some status on how many sites would be affected.

2. the `SimpleXML` API is more straightforward than the `XMLWriter` API, but `XMLWriter` is generally a little more performant in terms of the time it takes to generate an XML instance.    And if `XMLWriter` is used carefully, it can be much more performant in terms of memory for larger XML instance.

**Comment by pbiron** [comment]
I just raised this issue in the weekly [#hosting-community](https://wordpress.slack.com/archives/C3D6T7F8Q/p1582741877084400) meeting.

One participant there said he'd try to gather some internal stats and report back on how making `SimpleXML` (or `XMLWriter`) a required PHP extension would impact their customers.

And the person running the meeting suggested they can do a make/hosting post to try to gather more info.  She's gonna DM me later to get particulars.  So, anyone reading this, can you please add comments with specific questions you think it would be helpful to include in that make/hosting post?

**Comment by joemcgill** [comment]
My suggestion is that, unless we get overwhelming data showing that `SimpleXML` is unavailable on a large percentage of WP installations, we make it a requirement of _this_ feature specifically and provide a graceful failure message if that requirement is not met. It would not need to be a requirement of WordPress, since the application would still run just fine, it just would mean that someone without `SimpleXML` support would not benefit from Core's XML sitemap generation.

**Comment by Crixu** [comment]
Short update on the hoster situation:

1. I checked with IONOS and their latest PHP versions support the SimpleXML extension on their managed offerings
2. SimpleXML is a default with the latest PHP versions on Plesk servers.
3. 80% of cPanel servers have this module installed. cPanel installs it by default on new installs.
4. I talked with a Joomla! Extension developer about this. He is offering a popular plugin for Joomla! which requires the same extensions and never had a complain so far

**Comment by swissspidy** [comment]
@Crixu Thanks a lot for sharing! Very useful :)

**Comment by getsource** [comment]
Just for additional information, as [commented on the hosting team site](https://make.wordpress.org/hosting/2020/03/11/host-feedback-requested-regarding-simplexml/#comment-151):

I checked with folks, and heard back that SimpleXML is widely available across GoDaddy’s services. Feedback is that it seems reasonable to make it a requirement for the sitemaps feature.

**Comment by MazeWebArchitect** [comment]
RAIDBOXES has SimpleXML available on all Servers and we second that it is reasonable to require it for sitemaps.
