### ISSUE TITLE
Filter to disable XML Sitemaps feature

### ISSUE THREAD

**Issue by lukecav** [GoogleChromeLabs/wp-sitemaps#123]
If there is not one make sure there is a filter that can be used to disable the XML sitemaps feature.

**Comment by tangrufus** [comment]
Do we need anything more than `remove_action( 'init', 'core_sitemaps_get_server' );`?

See: https://github.com/GoogleChromeLabs/wp-sitemaps/blob/1b5fb5b4f0a2fb52952b4c945ae17062769ddb80/core-sitemaps.php#L49

**Comment by svandragt** [comment]
Maybe a check in `functions.php` to prevent the functions being available if the feature isn't hooked in.

**Comment by tangrufus** [comment]
So, something like this?


```php
add_action('some_hook', function(): void {
    $is_enable = apply_filters('is_xml_sitemap_enabled', true);
    if (! $is_enable) {
        return;
    }
  
    require_once __DIR__ . '/inc/functions.php';
    add_action( 'init', 'core_sitemaps_get_server' );
});
```


Question: Which hook should be using?
We want it to be before `init` and late enough for other plugins to filter `$is_enable`.

**Comment by swissspidy** [comment]
That means developers could never rely on these functions being available and have to use `function_exists` everywhere. That doesn't sound great.

IMO `remove_action( 'init', 'core_sitemaps_get_server' )` for now is enough. Alternatively a `core_sitemaps_enabled` filter within `core_sitemaps_get_server`. But no conditional file inclusion.

Similar to the (deprecated) `rest_enabled` filter.

**Comment by swissspidy** [comment]
Consolidating with #111. See #138.
