### ISSUE TITLE
Index the $url_list arrays by the ID (or term_id) if the items in the array

### ISSUE THREAD

**Issue by pbiron** [GoogleChromeLabs/wp-sitemaps#127]
### Description

The `core_sitemaps_posts_url_list`, `core_sitemaps_users_url_list` and `core_sitemaps_taxonomies_url_list` filters can be used to exclude specific posts, users and terms from the sitemap, but doing so is harder (and more expensive) than it should be.

**Describe the solution you'd like**

The arrays passed to these filters should be indexed by the `ID` (or `term_id`) of the items in the array.

For example, if I want to exclude the post with ID 123, I have to something like:
```
$post_id_to_exclude = 123;
$exclude = array_keys( wp_list_filter( $url_list, array( 'loc' => get_permalink( $post_id_to_exclude ) ) ) );
foreach ( $exclude as $idx ) {
	unset( $url_list[ $idx ] );
}
```

It would be **much**  easier if I could just do
```
unset( $url_list[ $post_id_to_exclude ] );
```

**Comment by swissspidy** [comment]
For **removing** entries one might be better off filtering the `WP_Query` instead of doing this.

Yes, it looks easy at first glance, and is faster, but is impractical if you wanna exclude many posts, or if someone doesn't index their entries when adding them. So if someone does something like this:

```php
$url_list[] = array(
	'loc'     => 'my-awesome-url',
	'lastmod' => '1970-..-..',
);
```

This could cause some troubles...

Example:

```php
$test = [
    187 => 'a',
    3 => 'a',
    99 => 'a',
];

$test[] = 'b';

var_dump($test);

/*
array(4) {
  [187]=>
  string(1) "a"
  [3]=>
  string(1) "a"
  [99]=>
  string(1) "a"
  [188]=>
  string(1) "b"
}
*/
```

**Comment by swissspidy** [comment]
Closing in favor of #131
