### ISSUE TITLE
Add filter to modify WP_Query arguments

### ISSUE THREAD

**Issue by swissspidy** [GoogleChromeLabs/wp-sitemaps#131]
### Description

Similar to what's suggested in https://wordpress.slack.com/archives/CTKTGNJJW/p1582058607135400, it might be easier to include/exclude to be able to adjust the `WP_Query` instance instead of having to rely on the `core_sitemaps_*_url_list` filters.

If you want to exclude a lot of posts from the sitemap, it's better to not query the DB for them in the first place.

**Describe the solution you'd like**

`do_action( 'core_sitemaps_...', &$query)` everywhere we use  `WP_Query` and `WP_Term_Query`.

**Additional context**
Add any other context or screenshots about the enhancement request here.

### Acceptance Criteria
Add the relevant acceptance criteria here.
- []
- []
- []

**Comment by pbiron** [comment]
Thanx for opening this issue, I've been meaning to do so, but other things got int the way.

As mentioned in Slack, I would prefer a `filter` on the args passed to the query objects, but that is just a preference and this would work as well.

What you suggest would be analogous to core's existing `parse_query` (for WP_Query) and `pre_user_query` (for WP_User_Query) actions.
