### ISSUE TITLE
Consider removing lastmod field

### ISSUE THREAD

**Issue by swissspidy** [GoogleChromeLabs/wp-sitemaps#133]
As discussed on Slack last week, calculating the last modified date for terms is rather difficult and computationally expensive in WordPress. Given that sitemaps are first and foremost a discovery mechanism for content, having this data is not necessarily required.

We should explore omitting this functionality, either completely or only for certain providers.

**Comment by chesio** [comment]
Note: This would inherently fix the issue described in #116.

**Comment by adamsilverstein** [comment]
As discussed in [slack](https://wordpress.slack.com/archives/CTKTGNJJW/p1584459887289200) today, the consensus is that removing `lastmod` simplifies things, solves issues and that overall `lastmod` is not needed. 

Regarding the _computationally expensive_ issue I wanted to mention the work we did in 5.2 for [get_feed_build_date](https://github.com/WordPress/wordpress-develop/blob/ac6cb23470ecd49d0eec4b3a16b921194cc5a4d1/src/wp-includes/feed.php#L663-L706). The code uses a relatively low cost approach to determine the latest date directly from the `wp_query` object, perhaps it could be used (or a similar approach) to solve the performance issue here?

**Comment by swissspidy** [comment]
`get_feed_build_date` essentially does `max( wp_list_pluck( $wp_query->posts, 'post_modified_gmt' ) )`. In `get_lastmod_for_type` we currently do  `get_post_modified_time( ..., $posts[0 _ )` on an ordered list, which is _basically_ the same. We just cache it.

**Comment by afragen** [comment]
As this seems the appropriate issue, I've been seeing many PHP notices in my log for the following. My line numbers don't match up as I have some debug code in there to output value of `$last_modifed`, FWIW it seems undefined.

> [03-Apr-2020 00:31:03 UTC] $last_modified:
> [03-Apr-2020 00:31:03 UTC] PHP Notice Undefined offset: 0 in /sites/food.thefragens.com/files/wp-content/plugins/core-sitemaps/inc/class-core-sitemaps-taxonomies.php on line 103
> [03-Apr-2020 00:31:03 UTC] PHP Notice Trying to get property 'post_modified_gmt' of non-object in /sites/food.thefragens.com/files/wp-content/plugins/core-sitemaps/inc/class-core-sitemaps-taxonomies.php on line 103
> 

This seems to be because the `$last_modified` variable is undefined. 

This might be related to custom CPTs on the site.
