### ISSUE TITLE
Update rewrite rules and query params to avoid plugin conflicts

### ISSUE THREAD

**Issue by ThierryA** [GoogleChromeLabs/wp-sitemaps#146]
**Describe the bug**
The [current rewrite rules](https://github.com/GoogleChromeLabs/wp-sitemaps/blob/cb1148d343abef399bd5b4bc472f58cbeeb3e67d/inc/class-core-sitemaps.php#L124) are conflicting with other plugins. We should change it it to avoid conflicts.
Query params may also need to be update, something to look into.

**To Reproduce**
1. Install Yoast SEO (one of the conflicting plugins

**Comment by swissspidy** [comment]
Closing as it was deemed to be a non-issue. If another plugin takes over, that's fine.
