### ISSUE TITLE
maybe flush rewrite rules when a custom provider is added

### ISSUE THREAD

**Issue by pbiron** [GoogleChromeLabs/wp-sitemaps#147]
When registering a custom provider I needed to manually flush rewrite rules before accessing the sitemap generated by that provider.

**To Reproduce**
1. register a custom provider with `core_sitemaps_register_providers`
2. go to `/wp-sitemap.xml`
3. click on the link for the custom provider
4. See the 404

**Expected behavior**
Step 3 should result in the custom provider's sitemap being rendered.

**Additional context**
I discovered this before updating to 0.2.0.  Haven't tested it since updating, but will.

**Comment by swissspidy** [comment]
I think instead of letting the provider set its desired route we just register a catch-all route. No need to flush any rules when adding/removing providers in that case.

**Comment by swissspidy** [comment]
@pbiron To answer your question on Slack, here's more or less what I had in mind...

Right now we do `add_rewrite_rule( '^wp-sitemap\.xml$', 'index.php?sitemap=index', 'top' )` in the main class, and every provider adds their own rewrites, e.g. `add_rewrite_rule( '^wp-sitemap-posts-([A-z]+)-?([0-9]+)?\.xml$', 'index.php?sitemap=posts&sub_type=$matches[1]&paged=$matches[2]', 'top' )` for the posts provider.

What we should do instead (untested!):

```php
add_rewrite_rule( '^wp-sitemap\.xml$', 'index.php?sitemap=index', 'top' );
add_rewrite_rule( '^wp-sitemap-([A-z]+)-?([A-z]+)-?([0-9]+)?\.xml$', 'index.php?sitemap=$matches[1]&sitemap_sub_type=$matches[2]&paged=$matches[3]', 'top' );
```

Providers then shouldn't have to worry about routes and URL slugs, just their object types and object sub types.
