### ISSUE TITLE
unit tests in sitemaps-renderer.php should not use string comparisons

### ISSUE THREAD

**Issue by pbiron** [GoogleChromeLabs/wp-sitemaps#156]
### Description

`test_get_sitemap_index_xml()` and `test_get_sitemap_xml()` fail on Windows because `SimpleXMLElement::asXML()` seems to use `\n` as a line ending and `$expected` uses `PHP_EOL`, which is `\n\r` on Windows.

But more to the point, the assertions should, as much as possible, be comparing [XML Information Set](https://www.w3.org/TR/2004/REC-xml-infoset-20040204/)s; that is, the abstract representations that an XML parser will see.

As written, these tests make assumptions about the serialization algorithm used by `SimpleXMLElement::asXML()` that are **not** documented and could change.

For example, in `test_get_sitemap_xml()` the assertions should pass if `$expected` were any of:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://' . WP_TESTS_DOMAIN . '/?sitemap-stylesheet=xsl" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-1</loc><lastmod>2019-11-01T12:00:00+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-2</loc><lastmod>2019-11-01T12:00:10+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-3</loc><lastmod>2019-11-01T12:00:20+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-4</loc><lastmod>2019-11-01T12:00:30+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-5</loc><lastmod>2019-11-01T12:00:40+00:00</lastmod></url>
</urlset>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://' . WP_TESTS_DOMAIN . '/?sitemap-stylesheet=xsl" ?>
<sitemap:urlset xmlnsns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap:url><sitemap:loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-1</sitemap:loc><sitemap:lastmod>2019-11-01T12:00:00+00:00</sitemap:lastmod></sitemap:url>
	<sitemap:url><sitemap:loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-2</sitemap:loc><sitemap:lastmod>2019-11-01T12:00:10+00:00</sitemap:lastmod></sitemap:url>
	<sitemap:url><sitemap:loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-3</sitemap:loc><sitemap:lastmod>2019-11-01T12:00:20+00:00</sitemap:lastmod></sitemap:url>
	<sitemap:url><sitemap:loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-4</sitemap:loc><sitemap:lastmod>2019-11-01T12:00:30+00:00</sitemap:lastmod></sitemap:url>
	<sitemap:url><sitemap:loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-5</loc><lastmod>2019-11-01T12:00:40+00:00</sitemap:lastmod></sitemap:url>
</urlset>
```

or even the very convoluted

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://' . WP_TESTS_DOMAIN . '/?sitemap-stylesheet=xsl" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:ns3='http://www.sitemaps.org/schemas/sitemap/0.9'>
	<ns0:url xmlns:ns0='http://www.sitemaps.org/schemas/sitemap/0.9'><ns1:loc xmlns:ns1='http://www.sitemaps.org/schemas/sitemap/0.9'>http://' . WP_TESTS_DOMAIN . '/2019/10/post-1</ns1:loc><lastmod>2019-11-01T12:00:00+00:00</lastmod></ns0:url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-2</loc><lastmod>2019-11-01T12:00:10+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-3</loc><lastmod>2019-11-01T12:00:20+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-4</loc><lastmod>2019-11-01T12:00:30+00:00</lastmod></url>
	<url><loc>http://' . WP_TESTS_DOMAIN . '/2019/10/post-5</loc><ns3:lastmod>2019-11-01T12:00:40+00:00</ns3:lastmod></url>
</urlset>
```

because an XML parser will see them all as the "same".

**Which feature is your enhancement request related to?**

#81

**Describe the solution you'd like**

PHPUnit has a couple of XML-related assertions, [assertXmlStringEqualsXmlString()](https://phpunit.readthedocs.io/en/9.0/assertions.html#assertxmlstringequalsxmlstring) and [assertEqualXMLStructure()](https://phpunit.readthedocs.io/en/9.0/assertions.html#assertequalxmlstructure).  Using either of those would get around the Windows line ending problem.  However, they aren't they aren't namespace-aware and so would still fail with the `$expected` values above :-(

The core test harness has an `xml_to_array()` function that will turn a string of XML into an array, which could be used (i.e., `assertEquals( xml_to_array( $expected ), xml_to_array( $xml ) )`.  But again, `xml_to_array()` doesn't do namespace-aware parsing; it also doesn't currently include processing instructions in the returned array (and so, as is, can't be used for tests that check whether stylesheets have been be disabled).  Luckily, both those problems can easily be solved in a way that I don't think would affect it's use in current core unit tests, e.g., those that test feeds.

There are better ways to write the kind of tests we need, but they would require that `DOMDocument` and/or `XSLTProcessor` were available in the test environment.  That's probably OK for the purposes of this feature plugin, but would they always be available for core tests (i.e., when we get merged into core)??

**Comment by pbiron** [comment]
I just found a few existing tests in the core test suite that do use `DOMDocument` (without having any `if ( class_exists( 'DOMDocument' ) ) {}` guards).  So it seems that using `DOMDocument` in tests shouldn't be a problem.  Anyone disagree?

How would that be useful?  For instance, the existing [test_get_sitemap_xml_extra_attributes()](https://github.com/GoogleChromeLabs/wp-sitemaps/blob/master/tests/phpunit/sitemaps-renderer.php#L135) isn't really testing what it appears to be testing.

It would be much better to replace it with something like:

```
/**
 * Ensure extra attributes added to URL lists are included in rendered XML.
 */
public function test_get_sitemap_xml_extra_attributes() {
	$url_list = array(
		array(
			'loc'     => 'http://' . WP_TESTS_DOMAIN . '/2019/10/post-1',
			'lastmod' => '2019-11-01T12:00:00+00:00',
			'string'  => 'value',
			'number'  => 200,
		),
	);

	$renderer = new Core_Sitemaps_Renderer();

	$xml = $renderer->get_sitemap_xml( $url_list );

	$xmlDOM = new DOMDocument();
	$this->assertTrue(
		$xmlDOM->loadXML( $xml ),
		 sprintf(
			'Sitemap is not well-formed XML: %s.',
			libxml_get_last_error() ? libxml_get_last_error()->message : ''
		)
	 );

	// of course, the XPath expressions below would need to be updated
	// when/if #151 is solved and extension elements are actually put into
	// extension namespaces :-)
	$xpath  = new DOMXpath( $xmlDOM );
	$xpath->registerNamespace( 'sitemap', 'http://www.sitemaps.org/schemas/sitemap/0.9' );

	$this->assertEquals(
		count( $url_list ),
		$xpath->evaluate( 'count( /sitemap:urlset/sitemap:url/sitemap:string )' ),
		'Extra string attributes are not being rendered in XML.'
	);
	$this->assertEquals(
		count( $url_list ),
		$xpath->evaluate( 'count( /sitemap:urlset/sitemap:url/sitemap:number )' ),
		'Extra number attributes are not being rendered in XML.'
	);

	foreach ( $url_list as $idx => $url_item ) {
		// XPath position() is 1-indexed, so incrememnt $idx.
		$idx++;

		$this->assertEquals(
			$url_item['string'],
			$xpath->evaluate( "string( /sitemap:urlset/sitemap:url[ {$idx} ]/sitemap:string )" ),
			'Extra string attributes are not being rendered in XML.'
		);
		$this->assertEquals(
			$url_item['number'],
			$xpath->evaluate( "string( /sitemap:urlset//sitemap:url[ {$idx} ]/sitemap:number )" ),
			'Extra number attributes are not being rendered in XML.'
		);
	}
}
```

It would require a little more than above, e.g., adding `setUp()` and `tearDown()` methods such as:

```
protected $libxml_default_error_handler;

public function setUp() {
	libxml_clear_errors();
	// Suppress warnings generated by DOMDocument::loadXML().
	$this->libxml_default_error_handler = libxml_use_internal_errors( true );
}

public function tearDown() {
	libxml_clear_errors();
	libxml_use_internal_errors( $this->libxml_default_error_handler );
}
```

to prevent `DOMDocument` from generating PHP warnings when loading non-well-formed XML, that would cause PHPUnit to report an error instead of failure,

**Comment by swissspidy** [comment]
Thanks for raising this @pbiron!

Improving the tests so that they at least work on Windows makes total sense to me. Namespace awareness would be a nice bonus, especially since we'd want to enable plugins to add namespaced attributes via filters. It should be fine to rely on `DOMDocument` for the tests.

**Comment by pbiron** [comment]
I'll try to find the time to open a PR before the meeting tomorrow.
