### ISSUE TITLE
Index Sitemap

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#16]
Sitemap index files (to group multiple sitemap files)

You can provide multiple Sitemap files, and they should be referenced by URL in a Sitemap index file. Sitemap index files may not list more than 50,000 Sitemaps and must be no larger than 50MB (52,428,800 bytes) and can be compressed. There will be one Sitemap index file. The XML format of a Sitemap index file is very similar to the XML format of a Sitemap file.

`<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>http://www.example.com/sitemap1.xml.gz</loc>
      <lastmod>2004-10-01T18:23:17+00:00</lastmod>
   </sitemap>
   <sitemap>
      <loc>http://www.example.com/sitemap2.xml.gz</loc>
      <lastmod>2005-01-01</lastmod>
   </sitemap>
</sitemapindex>`

XML Sitemaps will be _enabled by default_ making the following content types indexable:

Homepage
Posts page
Core Post Types (Pages and Posts)
Custom Post Types
Core Taxonomies (Tags and Categories)
Custom Taxonomies
Users (Authors)

Sitemap URLs, like all values in your XML files, must be entity escaped.

https://www.sitemaps.org/protocol.html#index

https://support.google.com/webmasters/answer/183668?hl=en

**Comment by joemcgill** [comment]
Initial work closed by #38. New issues are being created for follow-up work, like #60 and #71
