### ISSUE TITLE
Translation: need for '&rsaquo;' ?

### ISSUE THREAD

**Issue by ePascalC** [GoogleChromeLabs/wp-sitemaps#178]
In inc/class-core-sitemaps-renderer.php, line 185, the line says:
__( 'WordPress &rsaquo Error', 'core-sitemaps' )

Is there any specific requirement for having that &rsaquo ?

It will confuse translators and I'm not sure it fits well in that sentence.
(I remove the ; at the end of &rsaquo because GitHub was showing it directly as &rsaquo; )

**Comment by pbiron** [comment]
There are a couple of instances of that string in core, e.g. https://core.trac.wordpress.org/browser/trunk/src/wp-load.php#L92

**Comment by swissspidy** [comment]
Closing since we'd want consistency with already present strings in core.
