### ISSUE TITLE
Posts Sitemap

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#18]
The Sitemap must:

Begin with an opening <urlset> tag and end with a closing </urlset> tag.
Specify the namespace (protocol standard) within the <urlset> tag.
Include a <url> entry for each URL, as a parent XML tag.
Include a <loc> child entry for each <url> parent tag.

https://www.sitemaps.org/protocol.html

Implementation should be informed by performance considerations made previously in #1

Should paginate itself sequentially.

Not included:
Caching
Filters
Post status filters

**Comment by mcshanea** [comment]
Question: is it the responsibility of the plugin to verify all included URL's respond with a 200 http response?

**Comment by swissspidy** [comment]
That sounds like too much hand-holding for me.

Especially with extensibility (#25) in mind, it doesn't make sense to verify all included URLs. And I don't think any of the existing sitemap plugins do this.
