### ISSUE TITLE
get_sitemap_list() in Core_Sitemaps_Index throws an error when there are no sitemap entries for a provider

### ISSUE THREAD

**Issue by Rajesh-Techblissonline** [GoogleChromeLabs/wp-sitemaps#186]
**Describe the bug**
In class `Core_Sitemaps_Index`,  `get_sitemap_list()` function,  the following line throws an error when there are no sitemap entries for a provider as array_push expect a non-empty array.
`array_push( $sitemaps, ...$provider->get_sitemap_entries() );`

**To Reproduce**
1. No Taxonomies were selected for the Taxonomies provider i.e. `class-core-sitemaps-taxonomies.php` 
2. Try retrieving the sitemap
3. See error

**Expected behavior**
Error should not not be thrown when there are no sitemap entries for a provider. Instead, a sitemap should be generated for the other providers.

The solution is to check if $sitemap exists before doing an array push.

```php
public function get_sitemap_list() {
		$sitemaps = array();
		$providers = $this->registry->get_sitemaps();
		/* @var Core_Sitemaps_Provider $provider */
		foreach ( $providers as $provider ) {
			// Using array_push is more efficient than array_merge in a loop.                      
			$sitemap = $provider->get_sitemap_entries();
			//check if $sitemap exists
			if($sitemap) array_push( $sitemaps, ...$sitemap );
		}
		return $sitemaps;
	}
```

**Comment by swissspidy** [comment]
Which version of PHP are you using?

**Comment by swissspidy** [comment]
Looks like this is specific to PHP < 7.3 only:

https://www.php.net/manual/en/function.array-push.php
https://3v4l.org/Pk7En

**Comment by swissspidy** [comment]
Possible PR here: #190.

**Comment by Rajesh-Techblissonline** [comment]
> Which version of PHP are you using?

@swissspidy Yes, The warning is thrown in PHP Version 7.2
