### ISSUE TITLE
Rewrite rules may not get registered on multisite installs

### ISSUE THREAD

**Issue by westonruter** [GoogleChromeLabs/wp-sitemaps#205]
I noticed that the rewrite rules are only flushed on plugin activation:

https://github.com/GoogleChromeLabs/wp-sitemaps/blob/584efba4eb63e918bc691c92bc573bba8945f07b/core-sitemaps.php#L51-L75

What about if the plugin is network-activated on a multisite? Won't they fail to be recognized until the site manually flushes rewrite rules?

**Comment by swissspidy** [comment]
They‘re also flushed here: https://github.com/GoogleChromeLabs/wp-sitemaps/blob/master/inc/class-wp-sitemaps.php

**Comment by westonruter** [comment]
I suppose that would cause the rewrite rules to be flushed on multisite, but only when a request is made to one of the sites. The rewrite rule would get flushed while the request is being made to the frontend. That seems somewhat perilous.

**Comment by swissspidy** [comment]
Hmm not sure how much worth it is to dig into this as part of the plugin since we're already working the core patch: https://github.com/WordPress/wordpress-develop/pull/310

cc @felixarntz for Multisite expertise.

**Comment by westonruter** [comment]
Would the core patch rely on the DB upgrade prompt to ensure the rewrite rules are added?

**Comment by felixarntz** [comment]
See https://github.com/GoogleChromeLabs/pwa-wp/pull/289#discussion_r436293945 - I think to scale this in multisite it needs to happen in a hook per site, not an activation hook. But since this is on its way to core, probably not worth fixing in this case.

**Comment by westonruter** [comment]
@felixarntz but how is it being done in the core patch? How will a site's rewrite rules be updated upon upgrading? Does core flush rewrite rules as part of the DB upgrade routine?

**Comment by felixarntz** [comment]
@westonruter @swissspidy I think we'll need to add logic to the `upgrade_550` function (already in place on `trunk` for other reasons) that will `flush_rewrite_rules`.

**Comment by swissspidy** [comment]
Are we sure about that?

The REST API basically adds the rewrite rules the same way we do, see `rest_api_init` / `rest_api_register_rewrites`. And there's no `flush_rewrite_rules` in `upgrade_440`. In fact, there's no upgrade routine in core that flushes rewrites.

**Comment by felixarntz** [comment]
Does core somehow `flush_rewrite_rules` on update in general (outside of a specific routine)?

**Comment by swissspidy** [comment]
Ah, yes it does!

https://github.com/WordPress/wordpress-develop/blob/7a64133821012708eaa7a86c7677c67029a500e6/src/wp-admin/admin.php#L38-L48

So I think we are covered here for the core patch.
