### ISSUE TITLE
Not possible to add additional properties to the posts entry for the home page when 'posts' === get_option( 'show_on_front' )`

### ISSUE THREAD

**Issue by pbiron** [GoogleChromeLabs/wp-sitemaps#206]
### Description

When `'page' === $post_type && 1 === $page_num && 'posts' === get_option( 'show_on_front' )`, the posts provider adds a sitemap entry with `'loc' = home_url()`.  This is good.

But there is currently no way to add additional properties (e.g., `lastmod`) to that entry.

**Which feature is your enhancement request related to?**

#191 introduced the `wp_sitemaps_posts_entry` filter, but that filter is not applied to that entry.

**Describe the solution you'd like**

`wp_sitemaps_posts_entry` should be applied to that entry as well.  However, that filter is passed a `$post` and `$post_type` parameters, and there is nothing to pass in this case.

As a **convention**, we could pass `null` for both params and document that convention in the DocBlock of the filter.

Interested in other opinions for what we could do in this case.

**Comment by swissspidy** [comment]
Good catch!

Given that it‘s a special entry, perhaps we could give it its own filter?

Otherwise passing null seems ok too

**Comment by pbiron** [comment]
A new filter is probably best.

Any suggestions for the name of the new filter?  I'm thinking `wp_sitemaps_posts_show_on_front_entry`.

I'll throw together a PR.
