### ISSUE TITLE
Disable sitemap for ALL users.

### ISSUE THREAD

**Issue by wolffe** [GoogleChromeLabs/wp-sitemaps#211]
This is not an actual bug but I couldn't find any help on disabling the sitemap for ALL users, not one by one based on ID.

**Comment by pbiron** [comment]
Do you mean disable the users sitemap, but keep the posts and taxonomies (and any custom providers) sitemaps?

If you can do that with the `wp_sitemaps_register_providers` filter, as in:

```
add_filter(
	'wp_sitemaps_register_providers', 
	function( $providers ) {
		unset( $providers['users'] );

		return $providers;
	}
);
```

If that's not what you meant, can you please explain more :-)

**Comment by wolffe** [comment]
No, this might be it.

I'll try it today. I couldn't find this snippet anywhere and it looks like it will disable the users' sitemap.

Thanks!

**Comment by wolffe** [comment]
**Update:** It worked.

Is the `init` the best place to add these filters?

`add_action('init', 'sitemap_init', 3);`

I also have a sitemap plugin and I am trying to migrate to the new core functionality and get rid of mine.

**Comment by swissspidy** [comment]
It depends on what you want to do.

The `wp_sitemaps_register_providers` example given above works just fine as-is. You don't need to wait until `init` to add that filter. It wouldn't make any difference.

For more complex things, I recommend waiting until `wp_sitemaps_init`. Then you'll have access to the `WP_Sitemaps` instance, and know that sitemaps have been fully initialized and working. At this point, you can _add_ more providers, modify rendering, or remove filters. Here's an example:

```php
add_filter(
	'wp_sitemaps_register_providers', 
	function( $providers ) {
		unset( $providers['users'] );

		return $providers;
	}
);

add_action(
	'wp_sitemaps_init',
	function( $wp_sitemaps ) {
		// Do not add sitemap to robots.txt
		remove_filter( 'robots_txt', array( $wp_sitemaps, 'add_robots' ) );
	}
);
```

Note: `wp_sitemaps_init` runs _after_ `wp_sitemaps_register_providers`

**Comment by wolffe** [comment]
Okay, so I just dump that code into, say the `functions.php` file.

Thanks for `wp_sitemaps_init`, I'm learning more and more about this. I assume, a library of functions or snippets will be available prior to the WordPress 5.5 release.

**Comment by swissspidy** [comment]
`functions.php` works, but these things are not really theme-specific, so I'd recommend putting that into your custom sitemaps plugin that you appear to have.

**Comment by wolffe** [comment]
`functions.php` was just an example, but they will go into the sitemap plugin I have.

Going to close this now.
