### ISSUE TITLE
Spead operator in PHP 7.4 is used in sitemap index

### ISSUE THREAD

**Issue by rilwis** [GoogleChromeLabs/wp-sitemaps#214]
I see the spread operator for array is used in the [class-wp-sitemap-index.php](https://github.com/GoogleChromeLabs/wp-sitemaps/blob/master/inc/class-wp-sitemaps-index.php#L60) file:

```php
array_push( $sitemaps, ...$sitemap_entries );
```

This spread operator for array is added in [PHP 7.4](https://wiki.php.net/rfc/spread_operator_for_array). It might break in the older versions. The current PHP version required is 5.6 (and will be soon increase to 7.2, but still < 7.4).

Please consider changing it to keep sites working.

Thanks

**Comment by swissspidy** [comment]
You are confusing this with the splat operator for argument unpacking, which is supported since PHP 5.6.

See https://www.php.net/manual/en/migration56.new-features.php

**Comment by rilwis** [comment]
Ah, I got it. Thanks!
