### ISSUE TITLE
Custom Taxonomies Sitemap

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#22]
As a person or machine consuming the WP XML sitemaps, I should see links to the archive pages for all registered taxonomies that are marked as `public`.

## Acceptance requirements

- [ ] For each taxonomy, a `url` entry should be included for each term which contains a published public post.
- [ ] Each `url` entry should include a `loc` child entry containing the URL for that term's archive page (i.e., `get_term_link()`).
- [ ] Each `url` entry should include a `lastmod` child entry containing the modified date for the most recently updated post related to that term.
- [ ] Once a taxonomy sitemap page reaches 2000 `url` entries, a new sitemap page is created for that taxonomy type.

## Technical details

1. Update the `Core_Sitemaps_Categories` sitemap provider to be `Core_Sitemaps_Taxonomies` and add support for generating sitemaps for any public taxonomy.
2. The `$route` property should be updated to reference any taxonomy type, like `'^sitemap-taxonomies-([^-]+)-?([0-9]+)?\.xml$';` so that the first match group becomes the taxonomy type and the second match group becomes the paged parameter.
3. The `get_url_list()` method should be updated to use the taxonomy type parsed from the sitemap URL rather than hard coded.
4. The filter in `get_url_list()` should be renamed `core_sitemaps_taxonomies_url_list` and pass the taxonomy type as the second parameter.
5. The `render_sitemap` method should check to see if the specified taxonomy is public before rendering the sitemap and should return a 404 if the taxonomy doesn't exist or isn't public.

**Comment by joemcgill** [comment]
I've updated the issue description with more specific details on how to implement this in a way that should close #20 as well.

**Comment by joemcgill** [comment]
Addressed by #62.
