### ISSUE TITLE
Sitemap Priority

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#27]
### Description

The <priority> tag is used in XML sitemaps, by the webmaster, to signal the importance of individual pages in the website to Google and other search engines.

The priority of this URL relative to other URLs on your site. Valid values range from 0.0 to 1.0. This value does not affect how your pages are compared to pages on other sites—it only lets the search engines know which pages you deem most important for the crawlers.
The default priority of a page is 0.5.

### Acceptance Criteria

Add the relevant acceptance criteria here.

- [ ]
- [ ]
- [ ]

**Comment by swissspidy** [comment]
Just like `changefreq`, we should not add `priority` by default as it's not really used by search engines. That's why other plugins like Yoast SEO don't implement it either.

Sitemap entries can be filterable, so if someone really wants to have these fields, they could implement it themselves.

**Comment by joemcgill** [comment]
Closing based on @swissspidy's comment above.

**Comment by majestica** [comment]
hi, this is a relevant question for me now, i need to set individual priority values for pages, posts, categories, tags, can you show an example how can i implement this? Thanks

**Comment by swissspidy** [comment]
@majestica Please check out https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/ to learn about "Adding Additional Tags to Sitemap Entries"

**Comment by majestica** [comment]
> @majestica Please check out https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/ to learn about "Adding Additional Tags to Sitemap Entries"

i find about this and i write some snippet, but I just don't understand how to add different priority based on page type, post type, category etc

```
add_filter( 'wp_sitemaps_posts_entry', 'add_sitemap_tags', 25, 2 );
 
function add_sitemap_tags( $entry, $post ) {
 
	$entry[ 'priority' ] = '40%';
	$entry[ 'changefreq' ] = 'Monthly';
	$entry[ 'lastmod' ] = $post->post_modified_gmt;
 
	return $entry;
 
}
```

**Comment by swissspidy** [comment]
@majestica I recommend asking in the [WordPress.org support forums](https://wordpress.org/support/) as this repo here is not really monitored.
