### ISSUE TITLE
Main Class

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#36]
We need to have discuss an approach where sitemap providers can register themselves without adding any code to other classes, this is where potentially a Core_Sitemap class is needed, and is making development of additional Sitemap Providers more difficult, so that would be a good next task.

### Draft acceptance criterea

- [x] Sitemap provider registers an instance of itself without adding any code to the registry class.
- [x]  Index is able to iterate all registered sitemap providers.

_Originally posted by @svandragt in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/33_

**Comment by joemcgill** [comment]
Closed by #42.
