### ISSUE TITLE
Internationalisation 

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#4]
The XML Sitemaps will leverage standard internationalization functionality provided by WordPress core.

Since there are plans by WordPress leadership to officially support multilingual websites in WordPress, the XML Sitemaps will be flexible enough to list localized content in the future as per web development best practices.

**Comment by joemcgill** [comment]
@ThierryA the [project proposal](https://make.wordpress.org/core/2019/06/12/xml-sitemaps-feature-project-proposal/) includes a section on i18n, but doesn't go into specifics. For the purposes of the initial project, do we have any more specific requirements given that future plans for supporting multilingual sites are not yet fleshed out at a project level? 

I assume that we are ensuring that all text in the XSL file is translatable and all sitemaps are extendable by sites that are already providing different URLs based on localization preferences. Anything else that you are aware of?

**Comment by ThierryA** [comment]
Correct, as for today I don't seen anything else to do when it comes to Internationalisation.

**Comment by joemcgill** [comment]
Thanks for confirming. Going to close this ticket since it's purpose was requirements gathering.
