### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by kirstyburgoine** [GoogleChromeLabs/wp-sitemaps#43]
### Description

**Which feature is your enhancement request related to?**
https://github.com/GoogleChromeLabs/wp-sitemaps/issues/35 but affects all sitemaps.

**Describe the solution you'd like**
Each sitemap needs to have a `<lastmod>` date listed on the sitemap's index. Current thinking on how to approach this is:

> I think the index sitemap will list the buckets and each bucket is a cpt object so has its own post_modified_gmt which is when it was last updated with content, I don’t think it will get much more complex. That bit is missing currently, and then each bit of content registered with a sitemap provided will update its bucket

https://hmn.slack.com/archives/CNVN3ERGV/p1572873401010900

The timezone for each post currently being used on the posts sitemap is: `'lastmod'    => mysql2date( DATE_W3C, $post->post_modified_gmt, false ),`

**Additional context**
Needs some discussion as to whether honouring the `get_option( 'timezone_string' )` and fallback using `get_option( 'gmt_offset' )` is needed on the sitemap index, or is it overkill for the scope of this project

### Acceptance Criteria
Add the relevant acceptance criteria here.
- [ ] Display the last modified date on sitemap.xml for each sitemap listed

**Comment by svandragt** [comment]
May be fixed by #133
