### ISSUE TITLE
Index / PT Provider relationship

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#45]
Progress the difference (if any) between post-type and names and whether the index should derive from the same class.

What are the use cases for each and does there need to be a difference? Does Index derive from the Provider class?

_Originally posted by @svandragt in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/42/review_comment/create_

**Comment by swissspidy** [comment]
The functionality for the sitemap index and the individual sitemaps is currently heavily intertwined in various places. There are always some special checks for processing a sitemap with the name "index". This is a strong indicator that there should definitely be some separation of concerns as these are two different things with different features).

These special checks also prevent anyone from having a sitemap for a CPT called "index" by the way, which is not ideal either.

**Comment by svandragt** [comment]
Addressed via #51 

Summarized:
- Access providers via the registry, not the main class.
- The providers don't have to know about the registry.

**Comment by joemcgill** [comment]
@svandragt with #51 merged and new work being picked up in #71 (as a spinoff from #68), can this issue be closed?
