### ISSUE TITLE
Combine post type sitemaps

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#48]
### Description
Code for all post type sitemaps is very similar, so they can be combined into one class.

**Which feature is your enhancement request related to?**
#18 #17 #19 

**Describe the solution you'd like**
Loop through  system post types linked above and cpt then create sitemaps for each.

### Acceptance Criteria
Add the relevant acceptance criteria here.
- [] all acceptance critera of 17-19

**Comment by swissspidy** [comment]
We most likely want to still split up sitemaps of the `post` object type by the respective sub types (post, page, etc.). So the URLs and stuff would need to reflect that.

**Comment by joemcgill** [comment]
Ideally, we're going to end up with three main providers for core, which support the following object types:

1. Post Objects (i.e., posts, pages, CPTs)
2. Taxonomies (i.e., categories, tags, custom Taxonomies)
3. Users (i.e., authors)

Each object provider should include the ability to support multiple sub-types, so combining these two post types into a single provider should set up the architecture that will be repeated by the Taxonomy sitemap provider as well.
