### ISSUE TITLE
Combine taxonomies sitemaps

### ISSUE THREAD

**Issue by kirstyburgoine** [GoogleChromeLabs/wp-sitemaps#49]
### Description

**Which feature is your enhancement request related to?**
#20 #21 #22 

**Describe the solution you'd like**
Create sitemaps for each type of term but using one class to do.

### Acceptance Criteria
Add the relevant acceptance criteria here.
- [ ] All criteria for #20, #21, #22

**Comment by joemcgill** [comment]
I think we can handle this specifically via #22 and #20, so am going to close this ticket as redundant.
