### ISSUE TITLE
Review existing sitemap implementations

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#5]
Review the main implementations of sitemaps within the plugin ecosystem to determine recurring themes and help to define best practice.

### Acceptance Criteria
Report notable findings.
Consider Yoast, Google Sitemaps, and Jetpack.

**Comment by svandragt** [comment]
Is there a reason why the msm sitemap is not considered, seeing as it's the one built for performance? https://github.com/Automattic/msm-sitemap

**Comment by joemcgill** [comment]
@svandragt I don't think this was an intentional omission. I've included the msm-sitemap plugin in ones I've been looking at for prior art.

**Comment by joemcgill** [comment]
Research from this spike was documented in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/1#issuecomment-542823748.
