### ISSUE TITLE
Private posts / attachments?

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#54]
We should open an issue to discuss this a bit more in detail:

* What about private posts
* What about attachments (`inherit` post status)

View:
- Attachments can be added by a developer adding in an attachment provider.
- We're reviewing the codebase to review being able to filter the post status part of the query by a developer.

_Originally posted by @swissspidy in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/52_

**Comment by svandragt** [comment]
- Attachments can be added by a developer adding in an attachment provider.
- We're reviewing the codebase to review being able to filter the post status part of the query.

**Comment by swissspidy** [comment]
Attachments are explicitly excluded. 

Private posts are currently only listed when logged in, but that might be confusing. Let's hide them at all times.
