### ISSUE TITLE
Sitemaps without data should return 404

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#57]
[Updated by @joemcgill on 2019/11/18]

When viewing a sitemap page that doesn't include any URLs, the system should return a 404.

Currently, if you manually change the URL of a sitemap so that the page number is larger than what the system has generated, you will see a sitemap page with no entries. Instead, should we return a 404 or some other kind of error response to indicate that you've requested a page that doesn't exist?

**Comment by joemcgill** [comment]
I've updated the description to give more detail about what the current behavior is. I think the current behavior is ok for now, but a more precise handling might be useful, particularly if there are any implications for web crawlers. 

@swissspidy or @ThierryA, do you have any input on this?

**Comment by ThierryA** [comment]
Curious to hear how Jetpack and Yoast are handling that?

**Comment by joemcgill** [comment]
Jetpack returns an XML file that looks like this:

```
<error>
    <code>wp_die</code>
    <title>
        <![CDATA[ Sitemaps ]]>
    </title>
    <message>
        <![CDATA[
        No sitemap found. The system will try to build it again in 7 mins.
        ]]>
    </message>
    <data>
        <status>404</status>
    </data>
</error>
```

Yoast returns a 404.

**Comment by ThierryA** [comment]
Great, let's no re-invent the wheel on this one, 404 STGM 👍 (never though I would ever say a 404 sounds good :joy:)
