### ISSUE TITLE
Question: Remove support for `post_format` taxonomy type?

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wp-sitemaps#79]
**Describe the bug**
After #72, I noticed that the sitemap includes pages for the `post_format` taxonomy type, and the sitemap for that taxonomy type looks like this:

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>http://xml-sitemaps.local/type/gallery/</loc>
        <lastmod>2010-09-10T14:24:14+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/aside/</loc>
        <lastmod>2010-05-09T14:51:54+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/chat/</loc>
        <lastmod>2010-01-08T14:59:31+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/link/</loc>
        <lastmod>2010-03-07T15:06:53+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/image/</loc>
        <lastmod>2010-08-08T12:00:39+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/quote/</loc>
        <lastmod>2010-02-05T15:13:15+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/status/</loc>
        <lastmod>2010-04-04T15:21:24+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/video/</loc>
        <lastmod>2010-06-03T15:25:58+00:00</lastmod>
    </url>
    <url>
        <loc>http://xml-sitemaps.local/type/audio/</loc>
        <lastmod>2010-07-02T15:36:44+00:00</lastmod>
    </url>
</urlset>
```

**To Reproduce**
1. Import the [WP Theme Unit Test](https://codex.wordpress.org/Theme_Unit_Test) data or something similar to get posts that are set up for post formats.
1. Make use of a theme that supports post formats (most default themes will work)
1. See that sitemap-taxonomies-post_format-1.xml is listed in the sitemap index.
1. Visit `/sitemap-taxonomies-post_format-1.xml` and see URLs for each supported post format type.

**Expected behavior**
I thought this was surprising, but might be technically correct, since `post_format` is a public taxonomy and those URLs do return valid taxonomy archive pages.

Does this demonstrate an expectations gap on my part, does this expose a flaw in the logic we're using to determine which taxonomies to support (i.e., all public taxonomy types), or is this a special case that we need to account for like we do for `attachment` post types?

**Comment by kirstyburgoine** [comment]
When working on the taxonomies sitemaps, I made the decision to leave these in because they are core functionality. I don't know how well they are used, but as they are a part of core WordPress, I thought it better to leave them in and allow developers to filter them out rather than adding specific functionality to not support them.

**Comment by joemcgill** [comment]
Thanks @kirstyburgoine. They do seem like a valid taxonomy type to include. Let's go ahead and resolve this issue by agreeing that including the `post_format` taxonomy in sitemaps is expected behavior. We can always reopen this ticket later pending more feedback.
