### ISSUE TITLE
Instantiate development environment on HM hosting

### ISSUE THREAD

**Issue by mcshanea** [GoogleChromeLabs/wp-sitemaps#8]
As a person interested in testing/reviewing the plugin without needing to install it locally, I'd like to have a development environment available where I can see how sitemaps are being generated.

## Acceptance criteria

- [ ] TBD

**Comment by joemcgill** [comment]
I started stubbing out a description here. We'll need to decide if this is only for internal folks on our team to view or if we're wanting a site that is public. If the latter, we'll likely need some sort of vanity URL for this site.
