### ISSUE TITLE
Add user documentation and test coverage for available filters.

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wp-sitemaps#86]
### Description

This task is related to #25.

**Describe the solution you'd like**

For all of the implemented extensible features outlined in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334, we should add user documentation that shows examples of how someone would use each of the provided filters, and add test coverage to assure these filters continue working as expected.

**Additional context**
Add any other context or screenshots about the enhancement request here.

### Acceptance Criteria

- [ ] All filters listed in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334 have PHPUnit tests.
- [ ] User examples for all filters listed in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334 are included in the README file or additional docs.

**Comment by joemcgill** [comment]
Additional test coverage for the following use cases would be useful:

- [ ] Provide a custom XML Stylesheet
- [ ] Exclude a specific post type from the sitemap
- [ ] Exclude a specific post from the sitemap
- [ ] Exclude a specific taxonomy from the sitemap
- [ ] Exclude a specific term from the sitemap
- [ ] Exclude a specific author from the sitemap
- [ ] Exclude a specific authors with a specific role from the sitemap

@swissspidy we intentionally prioritized the implementation/test coverage of #87, #88, and #81 over creating documentation. Would you like to split that task out into a separate ticket or combine it with this one?

**Comment by svandragt** [comment]
This will be taken forward in a separate discussion, I will leave it open for the future.

**Comment by felixarntz** [comment]
I've iterated on the PR #124, which should be good for review now.
