### ISSUE TITLE
Clarify variable/property names

### ISSUE THREAD

**Issue by joemcgill** [GoogleChromeLabs/wp-sitemaps#91]
### Description

**Which feature is your enhancement request related to?**
Sitemap providers

**Describe the solution you'd like**
There are several places throughout the codebase where the verbiage around type, subtype, slug, object type, etc. is unclear, leading to function signatures where methods are expecting values like `$name` which are actually referring to the object type or subtype. This is confusing and requires developers to understand the implicit design intent of a property or variable rather than using explicit naming to make the intent clear.

We should update the names of properties and functional variables within all providers to denote object type or object sub-type explicitly and remove references to `$name` and `$slug` throughout those systems, unless those variable/property names have an intentional meaning.

### Acceptance Criteria
Add the relevant acceptance criteria here.
- []
- []
- []

**Comment by felixarntz** [comment]
Another related point is that we should change all functions and methods to use `subtype` rather than `sub_type` - core does not split this word in code.

**Comment by felixarntz** [comment]
And, the object types used here are partially incorrect, object types are `post`, `term`, `user`, not `posts`, `taxonomies`, `users`.

**Comment by swissspidy** [comment]
@felixarntz yeah we might need to rename those properties. They're pluralized so they look better in URLs.

**Comment by felixarntz** [comment]
@swissspidy Yeah, we can also use different names for URL purposes, but the actual slugs for object types shouldn't be changed from how core has them.

**Comment by felixarntz** [comment]
PR is ready for review #174
